apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: falamarcaodocker/kub-demo-tasks:1.1
        env:
          - name: TASKS_FOLDER
            value: tasks
          - name: AUTH_ADDRESS
            value: auth-service.default
