apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: falamarcaodocker/kub-demo-users:1.4
          env:
            - name: AUTH_ADDRESS
              # value: "10.105.109.73"
              value: auth-service.default
